### ISSUE TITLE
Change branch name from "master" to "main"

### ISSUE THREAD

**Issue by MaikNog** [MaibornWolff/evmuncher#3]
Hi, 
    as a small contribution, maybe the naming could be changed.
    https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx“

    "git branch -m master main"
    "git push -u origin main"

**Comment by jacekv** [comment]
Done :)

**Comment by MaikNog** [comment]
@jacekv 
Do you plan to make "main" the default branch?

**Comment by jacekv** [comment]
@MaikNog main is now the default branch
